
export const SHOW_ALL = 'SHOW_ALL';
export const ENABLE_SHOW_UNDERTHIRTY = 'ENABLE_SHOW_UNDERTHIRTY';
export const ENABLE_SHOW_OVERTHIRTY = 'ENABLE_SHOW_OVERTHIRTY';
export const ENABLE_SHOW_MALE = 'ENABLE_SHOW_MALE';
export const ENABLE_SHOW_FEMALE = 'ENABLE_SHOW_FEMALE';

export const DISABLE_SHOW_UNDERTHIRTY = 'DISABLE_SHOW_UNDERTHIRTY';
export const DISABLE_SHOW_OVERTHIRTY = 'DISABLE_SHOW_OVERTHIRTY';
export const DISABLE_SHOW_MALE = 'DISABLE_SHOW_MALE';
export const DISABLE_SHOW_FEMALE = 'DISABLE_SHOW_FEMALE';

export const setVisibilityFilter = filter => ({
  type: filter,
  filter
});
